name: treecon

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run analysis in all packages.

  test: 
    run: melos exec --dir-exists="test" -- flutter test
    description: Run tests in packages that have tests.


